 pipeline
   {

		agent any
		  stages {
		      stage('Pull') {
			   steps{
			      script{
				  checkout([$class: 'GitSCM', branches: [[name: '*/main']],
				      userRemoteConfigs: [[
					  url: 'https://github.com/walid1919/CD.git']]])
			      }
		          }
		     }
	     }
	     }
